version: "3"

services:
  db:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - db-data-volume:/pg_data
    environment:
      - PGDATA=/pg_data
      - POSTGRES_DB=${DB_NAME:-db}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "$DB_NAME"]
      interval: 30s
      timeout: 30s
      retries: 3

  http:
    image: lms:latest
    #    command: gunicorn --bind 0.0.0.0:80 --workers 5 lmsweb
    command: sleep 3600
    volumes:
      - ../lmsweb:/opt/lms/lmsweb
      - ../lmsdb:/opt/lms/lmsdb
      - ../static:/opt/lms/static
      - ../templates:/opt/lms/templates
      - ../static/opt/lms/static
    environment:
      - DB_NAME=${DB_NAME:-db}
      - DB_USER=${DB_USERNAME:-postgres}
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
    links:
      - db
    ports:
      - 80:80
    depends_on:
      - db

volumes:
  db-data-volume:
