version: "3"

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db-data-volume:/pg_data
    environment:
      - PGDATA=/pg_data/14/data
      - POSTGRES_DB=${DB_NAME:-db}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USERNAME -d $DB_NAME"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - lms

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    hostname: celery-mq
    volumes:
      - rabbit-data-volume:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq.cookie:/var/lib/rabbitmq/.erlang.cookie
    networks:
      - lms

  checks-sandbox:
    image: lms:latest
    command: celery -A lms.lmstests.sandbox worker
    volumes:
      - ../lms/lmstests/sandbox/:/app_dir/lms/lmstests/sandbox/
    environment:
      - CELERY_RABBITMQ_ERLANG_COOKIE=AAVyo5djdSMGIZXiwEQs3JeVaBx5l14z
      - CELERY_RABBITMQ_DEFAULT_USER=rabbit-user
      - CELERY_RABBITMQ_DEFAULT_PASS=YgKlCvnYVzpTa3T9adG3NrMoUNe4Z5aZ
      - CELERY_CHECKS_SANDBOX_VHOST=lmstests-sandbox
      - CELERY_RABBITMQ_HOST=rabbitmq
      - CELERY_RABBITMQ_PORT=5672
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - lms

  checks-docker-engine:
    image: docker:dind
    privileged: True
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-engine-volume-run:/var/run/
      - docker-engine-certs:/certs
      - docker-engine-lib:/var/lib/docker
    networks:
      - lms

  checks-public:
    image: lms:latest
    command: celery -A lms.lmstests.public worker
    volumes:
      - ../lms:/app_dir/lms/
      - docker-engine-volume-run:/var/run/
      - docker-engine-certs:/certs
      - docker-engine-lib:/var/lib/docker
    environment:
      - DB_NAME=${DB_NAME:-db}
      - DB_USER=${DB_USERNAME:-postgres}
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - CELERY_RABBITMQ_ERLANG_COOKIE=AAVyo5djdSMGIZXiwEQs3JeVaBx5l14z
      - CELERY_RABBITMQ_DEFAULT_USER=rabbit-user
      - CELERY_RABBITMQ_DEFAULT_PASS=YgKlCvnYVzpTa3T9adG3NrMoUNe4Z5aZ
      - CELERY_CHECKS_PUBLIC_VHOST=lmstests-public
      - CELERY_CHECKS_SANDBOX_VHOST=lmstests-sandbox
      - CELERY_RABBITMQ_HOST=rabbitmq
      - CELERY_RABBITMQ_PORT=5672
    links:
      - db
      - rabbitmq
    depends_on:
      - db
      - rabbitmq
    networks:
      - lms

  http:
    image: lms:latest
    command: gunicorn --reload --bind 0.0.0.0:8080 --workers 5 lms.lmsweb
    volumes:
      - ../lms:/app_dir/lms
      - ../../notebooks-tests:/app_dir/notebooks-tests
      - repositories-data-volume:/repositories
    environment:
      - DB_NAME=${DB_NAME:-db}
      - DB_USER=${DB_USERNAME:-postgres}
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - CELERY_RABBITMQ_ERLANG_COOKIE=AAVyo5djdSMGIZXiwEQs3JeVaBx5l14z
      - CELERY_RABBITMQ_DEFAULT_USER=rabbit-user
      - CELERY_RABBITMQ_DEFAULT_PASS=YgKlCvnYVzpTa3T9adG3NrMoUNe4Z5aZ
      - CELERY_CHECKS_PUBLIC_VHOST=lmstests-public
      - CELERY_RABBITMQ_HOST=rabbitmq
      - CELERY_RABBITMQ_PORT=5672
      - REPOSITORY_FOLDER=/repositories
    links:
      - db
      - rabbitmq
    ports:
      - 8080:8080
    depends_on:
      - db
      - rabbitmq
    networks:
      - lms

volumes:
  docker-engine-volume-run:
  docker-engine-certs:
  docker-engine-lib:
  db-data-volume:
  rabbit-data-volume:
  repositories-data-volume:


networks:
  lms:
    external:
      name: lms
