language: python
cache: pip

dist: xenial
python: 
  - 3.6
  - 3.7
install: pip install -r requirements.txt

matrix:
  include:
    - name: "Python Lint"
      script:
      - flake8
      - mypy . --ignore-missing-imports
