name: CI checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev_requirements.txt
        wget https://github.com/validator/validator/releases/download/20.6.30/vnu.linux.zip
        unzip vnu.linux.zip -d /opt/vnu/
        chmod +x /opt/vnu/vnu-runtime-image/bin/vnu
    - name: Lint
      run: |
        flake8 lms --ignore Q000,I202,W503,S101,I100,I101,E800 --import-order-style=google --count --show-source --statistics
    - name: Test
      run: |
        export PYTHONPATH=`pwd`
        export PATH=/opt/vnu/vnu-runtime-image/bin:$PATH
        pytest -vvv --junitxml=junit/test-results.xml --cov-report=xml --cov=lms ./tests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.13
      with:
        file: coverage.xml
